apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zen-watcher.fullname" . }}-config
  namespace: {{ include "zen-watcher.namespace" . }}
  labels:
    {{- include "zen-watcher.labels" . | nindent 4 }}
data:
  CLUSTER_ID: {{ .Values.global.clusterID | quote }}
  WATCH_NAMESPACE: {{ .Values.config.watchNamespace | quote }}
  BEHAVIOR_MODE: {{ .Values.config.behaviorMode | quote }}
  TRIVY_NAMESPACE: {{ .Values.config.trivyNamespace | quote }}
  FALCO_NAMESPACE: {{ .Values.config.falcoNamespace | quote }}


