---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "zen-agent.watcher.fullname" . }}
  labels:
    {{- include "zen-agent.watcher.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "zen-agent.watcher.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "zen-agent.watcher.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

