---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zen-agent.watcher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zen-agent.watcher.labels" . | nindent 4 }}

