apiVersion: v2
name: zen-agent
description: Zen Agent - Kubernetes remediation and observability agent
type: application
version: 0.1.1
appVersion: "bootstrap"
maintainers:
  - name: Kube Zen Team
    url: https://kube-zen.io
keywords:
  - observability
  - remediation
  - kubernetes
home: https://kube-zen.io
sources:
  - https://github.com/kube-zen/zen-agent
